### ISSUE TITLE
Problem with installing requirements

### ISSUE THREAD

**Issue by haohaohtc2010** [niklastoe/classifier_metric_uncertainty#2]
When I tried to install this project locally, it showed error, the error message below:
![1](https://user-images.githubusercontent.com/28436639/235693519-3b886a0e-e206-4fcf-b975-17b9bcc228a6.jpg)

**Comment by haohaohtc2010** [comment]
Error message in text:
ERROR: Command errored out with exit status 1: /home/hammer/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1qxojdu3/pandas_9463695615b443ab9140a7e3808a1703/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1qxojdu3/pandas_9463695615b443ab9140a7e3808a1703/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-nss6suyu/install-record.txt --single-version-externally-managed --compile --install-headers /home/hammer/anaconda3/include/python3.9/pandas Check the logs for full command output.

**Comment by niklastoe** [comment]
If I understand your error message correctly, you are facing this problem while trying to install the package, not the requirements, right?

The package does not have a setup.py file so it cannot be installed. You can use it by adding the location of the package on your local machine to your python path as discussed on e.g. https://stackoverflow.com/questions/3402168/permanently-add-a-directory-to-pythonpath

The easiest (but not elegant) way to do this 

```
import sys
sys.path.append("/your/path/to/classifier_metric_uncertainty/")
from classifier_metric_uncertainty import ConfusionMatrixAnalyser 
```

Then you can use it in the usual way.

**Comment by haohaohtc2010** [comment]
I met this problem when I executed "pip install -r requirements.txt". I think it is on requirements.
